### ISSUE TITLE
Error Publishing: 503 No Responders Available For Request

### ISSUE THREAD

**Issue by pg-yang** [nats-io/nats.java#708]
I use jdk1.8 and nats java client 2.15.6 . nats-server running in docker container, as follow :
```
version: '3.8'
services:
  nats-server:
    image: nats:2.8.4-alpine3.15
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    entrypoint:
      - nats-server
      - "--auth"
      - "abcdefgh"
      - "--jetstream"
      - "-D"%    
```

Error stack 

```
java.io.IOException: Error Publishing: 503 No Responders Available For Request
	at io.nats.client.impl.NatsJetStream.processPublishResponse(NatsJetStream.java:153) ~[jnats-2.15.6.jar:2.15.6]
	at io.nats.client.impl.NatsJetStream.publishSyncInternal(NatsJetStream.java:123) ~[jnats-2.15.6.jar:2.15.6]
	at io.nats.client.impl.NatsJetStream.publish(NatsJetStream.java:61) ~[jnats-2.15.6.jar:2.15.6]

```

Code 

```
        try {
            JetStream js = connection.jetStream();
            StreamUtil.initStream(connection, subject, stream);
            PublishAck pa = js.publish(msg);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
```
```
    public static void initStream(Connection connection, String subject, String stream) throws Exception {

        JetStreamManagement jetStreamManagement = connection.jetStreamManagement();
        StreamInfo streamInfo;
        try {
            streamInfo = jetStreamManagement.getStreamInfo(stream);
        } catch (JetStreamApiException e) {
            streamInfo = null;
        }

        if (streamInfo == null) {
            StreamConfiguration sc = StreamConfiguration.builder()
                    .name(stream)
                    .storageType(StorageType.Memory)
                    .subjects(subject)
                    .build();
            jetStreamManagement.addStream(sc);
        } else {
            List<String> subjects = streamInfo.getConfiguration().getSubjects();
            if (!subjects.contains(subject)) {
                subjects.add(subject);
                jetStreamManagement.updateStream(streamInfo.getConfiguration());
            }
        }
    }
```
